spring:
  datasource:

    url: jdbc:postgresql://localhost:5400/fixdev_blog
    username: fixdev
    password: fixdev_dev
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-secret: Awo49QjjVy8uXEYbZPMFYRgrhpJx3cll
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/fixdev

app:
  media:
    upload-dir: ./dev-uploads

server:
  port: 8090
