services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: fixdev_blog
      POSTGRES_USER: fixdev
      POSTGRES_PASSWORD: fixdev_dev
    ports:
      - "5400:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/fixdev_blog
      KC_DB_USERNAME: fixdev
      KC_DB_PASSWORD: fixdev_dev
      KC_HTTP_PORT: 8181
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8181"
    depends_on:
      -    postgres

volumes:
  pgdata:


